apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .env: REFUQUJBU0VfVVJMPSJteXNxbDovL2Vjb20tZGI6MzMwNi9zaG9wIgpDQUNIRV9TSVpFPSIxMDAwIgpQQVlNRU5UX0dBVEVXQVlfVVJMPSJodHRwczovL3BheW1lbnQtZ2F0ZXdheS5leGFtcGxlLmNvbSIKTUFYX0NBUlRfSVRFTVM9IjUwIgpTRVNTSU9OX1RJTUVPVVQ9IjM3MDAi
  cache: REFUQUJBU0VfVVJMPSJteXNxbDovL2Vjb20tZGI6MzMwNi9zaG9wIgpDQUNIRV9TSVpFPSIxMDAwIgpQQVlNRU5UX0dBVEVXQVlfVVJMPSJodHRwczovL3BheW1lbnQtZ2F0ZXdheS5leGFtcGxlLmNvbSIKTUFYX0NBUlRfSVRFTVM9IjUwIgpTRVNTSU9OX1RJTUVPVVQ9IjM3MDAi
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  containers:
    - name: dotfile-test-container
      image: nginx
      volumeMounts:
        - name: env-file
          readOnly: true
          mountPath: "/etc/secret-volume"
  volumes:
    - name: env-file
      secret:
        secretName: dotfile-secret
